CREATE TABLE Producto (
    id_producto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    modelo VARCHAR2(100),
    marca VARCHAR2(100),
    descripcion VARCHAR2(255)
);

-- Poblar la tabla con 10 registros
INSERT INTO Producto (modelo, marca, descripcion) VALUES ('Carpa', 'MarcaA', 'Carpa de 2 personas');
INSERT INTO Producto (modelo, marca, descripcion) VALUES ('Carpa', 'MarcaB', 'Carpa de 4 personas');
// ... otros registros
